<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/BidEuchre.Protocol/BidEuchre.Protocol.csproj" />
    <ProjectReference Include="../../src/BidEuchre.App/BidEuchre.App.csproj" />
  </ItemGroup>

</Project>
